services:
  - type: web
    name: Life_Assistant # 你的服務名稱
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free # 如果你是付費版改 starter
    buildpacks:
      - key: python
      - url: https://github.com/jkutner/heroku-buildpack-google-chrome